# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OptionsFrame = QtWidgets.QFrame(self.centralwidget)
        self.OptionsFrame.setStyleSheet("background-color: rgb(227, 220, 204);\n"
"color: rgb(0, 0, 0);")
        self.OptionsFrame.setObjectName("OptionsFrame")
        self.OptionsFrame_2 = QtWidgets.QVBoxLayout(self.OptionsFrame)
        self.OptionsFrame_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.OptionsFrame_2.setContentsMargins(0, 0, 0, 0)
        self.OptionsFrame_2.setSpacing(0)
        self.OptionsFrame_2.setObjectName("OptionsFrame_2")
        self.Options_TopButtons = QtWidgets.QHBoxLayout()
        self.Options_TopButtons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.Options_TopButtons.setContentsMargins(5, 0, 5, -1)
        self.Options_TopButtons.setSpacing(6)
        self.Options_TopButtons.setObjectName("Options_TopButtons")
        self.Opt_OpenButton = QtWidgets.QPushButton(self.OptionsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Opt_OpenButton.sizePolicy().hasHeightForWidth())
        self.Opt_OpenButton.setSizePolicy(sizePolicy)
        self.Opt_OpenButton.setMouseTracking(False)
        self.Opt_OpenButton.setStyleSheet("QPushButton {\n"
"    border: 3px solid black;\n"
"    border-radius: 8px;\n"
"    padding:8px 8px;\n"
"\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,0,0,.2)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0,0,0,.4)\n"
"}")
        self.Opt_OpenButton.setDefault(False)
        self.Opt_OpenButton.setObjectName("Opt_OpenButton")
        self.Options_TopButtons.addWidget(self.Opt_OpenButton)
        self.Opt_PauseButton = QtWidgets.QPushButton(self.OptionsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Opt_PauseButton.sizePolicy().hasHeightForWidth())
        self.Opt_PauseButton.setSizePolicy(sizePolicy)
        self.Opt_PauseButton.setStyleSheet("QPushButton {\n"
"    border: 3px solid black;\n"
"    border-radius: 8px;\n"
"    padding:8px 8px;\n"
"    color: white;\n"
"    background-color: rgb(85, 85, 255);\n"
"\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 180)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(27, 27, 80)\n"
"}")
        self.Opt_PauseButton.setObjectName("Opt_PauseButton")
        self.Options_TopButtons.addWidget(self.Opt_PauseButton)
        self.Opt_RecButton = QtWidgets.QPushButton(self.OptionsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Opt_RecButton.sizePolicy().hasHeightForWidth())
        self.Opt_RecButton.setSizePolicy(sizePolicy)
        self.Opt_RecButton.setStyleSheet("QPushButton {\n"
"    border: 3px solid black;\n"
"    border-radius: 8px;\n"
"    padding:8px 8px;\n"
"    color: white;\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(180, 0, 0)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(80, 0, 0)\n"
"}")
        self.Opt_RecButton.setObjectName("Opt_RecButton")
        self.Options_TopButtons.addWidget(self.Opt_RecButton)
        self.OptionsFrame_2.addLayout(self.Options_TopButtons)
        self.checkboxesLayout = QtWidgets.QGridLayout()
        self.checkboxesLayout.setObjectName("checkboxesLayout")
        self.OptionsFrame_2.addLayout(self.checkboxesLayout)
        self.slidersLayout = QtWidgets.QVBoxLayout()
        self.slidersLayout.setObjectName("slidersLayout")
        self.OptionsFrame_2.addLayout(self.slidersLayout)
        self.MainFrame_2 = QtWidgets.QFrame(self.OptionsFrame)
        self.MainFrame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.MainFrame_2.setObjectName("MainFrame_2")
        self.MainFrame = QtWidgets.QVBoxLayout(self.MainFrame_2)
        self.MainFrame.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.MainFrame.setContentsMargins(0, 0, 0, 0)
        self.MainFrame.setObjectName("MainFrame")
        self.lcdNumber = QtWidgets.QLCDNumber(self.MainFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 50))
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: white;")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.MainFrame.addWidget(self.lcdNumber)
        self.horizontalSlider = QtWidgets.QSlider(self.MainFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setSizeIncrement(QtCore.QSize(0, 0))
        self.horizontalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider.setAutoFillBackground(False)
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.MainFrame.addWidget(self.horizontalSlider)
        self.OptionsFrame_2.addWidget(self.MainFrame_2)
        self.horizontalLayout_2.addWidget(self.OptionsFrame)
        self.ImageFraming = QtWidgets.QFrame(self.centralwidget)
        self.ImageFraming.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ImageFraming.setObjectName("ImageFraming")
        self.ImageFraming_2 = QtWidgets.QVBoxLayout(self.ImageFraming)
        self.ImageFraming_2.setObjectName("ImageFraming_2")
        self.label = QtWidgets.QLabel(self.ImageFraming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ImageFraming_2.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.ImageFraming)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Video_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Video_Image.setObjectName("actionOpen_Video_Image")
        self.actionOpen_Image_URL = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image_URL.setObjectName("actionOpen_Image_URL")
        self.actionAbout_ntscQT = QtWidgets.QAction(MainWindow)
        self.actionAbout_ntscQT.setObjectName("actionAbout_ntscQT")
        self.menuFile.addAction(self.actionOpen_Video_Image)
        self.menuFile.addAction(self.actionOpen_Image_URL)
        self.menuAbout.addAction(self.actionAbout_ntscQT)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Opt_OpenButton.setText(_translate("MainWindow", "OPEN"))
        self.Opt_PauseButton.setText(_translate("MainWindow", "PAUSE"))
        self.Opt_RecButton.setText(_translate("MainWindow", "REC"))
        self.label.setText(_translate("MainWindow", "No image/video/GIF selected. ❓"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Video_Image.setText(_translate("MainWindow", "Open Video/Image"))
        self.actionOpen_Image_URL.setText(_translate("MainWindow", "Open Image URL"))
        self.actionAbout_ntscQT.setText(_translate("MainWindow", "About ntscQT"))
